In [4]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np 

In [5]:
dataFrame = pd.read_csv('Data_Set.csv')

In [6]:
dataFrame

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [7]:
dataset = dataFrame.values

In [8]:
dataset

array([[8.420e+02, 0.000e+00, 2.200e+00, ..., 0.000e+00, 1.000e+00,
        1.000e+00],
       [1.021e+03, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       [5.630e+02, 1.000e+00, 5.000e-01, ..., 1.000e+00, 0.000e+00,
        2.000e+00],
       ...,
       [1.911e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 0.000e+00,
        3.000e+00],
       [1.512e+03, 0.000e+00, 9.000e-01, ..., 1.000e+00, 1.000e+00,
        0.000e+00],
       [5.100e+02, 1.000e+00, 2.000e+00, ..., 1.000e+00, 1.000e+00,
        3.000e+00]])

In [9]:
X_var = dataset[:,0:20]

In [10]:
Y_var = dataset[:,20]

In [11]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scl = min_max_scaler.fit_transform(X_var)

In [12]:
X_scl

array([[0.22778891, 0.        , 0.68      , ..., 0.        , 0.        ,
        1.        ],
       [0.34736139, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       [0.04141617, 1.        , 0.        , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.94188377, 0.        , 0.16      , ..., 1.        , 1.        ,
        0.        ],
       [0.6753507 , 0.        , 0.16      , ..., 1.        , 1.        ,
        1.        ],
       [0.00601202, 1.        , 0.6       , ..., 1.        , 1.        ,
        1.        ]])

In [13]:
Y_var = dataFrame['price_range']

In [14]:
X_training, X_valid_and_test, Y_training, Y_valid_and_test = train_test_split(X_scl, Y_var, test_size=0.2 , random_state=42)

In [15]:
 X_valid_and_test

array([[0.76486306, 0.        , 0.8       , ..., 1.        , 1.        ,
        0.        ],
       [0.45490982, 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.98263193, 0.        , 0.96      , ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.36272545, 0.        , 0.52      , ..., 1.        , 1.        ,
        1.        ],
       [0.15163661, 0.        , 0.88      , ..., 1.        , 1.        ,
        1.        ],
       [0.45691383, 0.        , 0.56      , ..., 1.        , 1.        ,
        1.        ]])

In [16]:
X_valid, X_testing, Y_valid, Y_testing = train_test_split(X_valid_and_test, Y_valid_and_test, test_size=0.5)

In [17]:
print(X_training.shape, X_valid.shape, X_testing.shape, Y_training.shape, Y_valid.shape, Y_testing.shape)

(1600, 20) (200, 20) (200, 20) (1600,) (200,) (200,)


In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import SparseCategoricalCrossentropy
from keras.optimizers import Adam

model = Sequential([
 Dense(10, activation="relu", input_shape=(20,)),
 Dense(15,activation='relu'),
 Dense(4,activation='softmax')
])
model.compile(
   loss = SparseCategoricalCrossentropy(),
   optimizer = Adam(),
   metrics="accuracy")

In [19]:
model.fit(X_training,Y_training,epochs=25)

Epoch 1/25
50/50 [==============================] - 2s 3ms/step - loss: 1.4322 - accuracy: 0.2425
Epoch 2/25
50/50 [==============================] - 0s 2ms/step - loss: 1.3883 - accuracy: 0.2912
Epoch 3/25
50/50 [==============================] - 0s 2ms/step - loss: 1.3604 - accuracy: 0.3106
Epoch 4/25
50/50 [==============================] - 0s 2ms/step - loss: 1.3284 - accuracy: 0.3506
Epoch 5/25
50/50 [==============================] - 0s 2ms/step - loss: 1.2779 - accuracy: 0.3869
Epoch 6/25
50/50 [==============================] - 0s 2ms/step - loss: 1.2047 - accuracy: 0.4375
Epoch 7/25
50/50 [==============================] - 0s 2ms/step - loss: 1.1200 - accuracy: 0.5269
Epoch 8/25
50/50 [==============================] - 0s 2ms/step - loss: 1.0299 - accuracy: 0.5650
Epoch 9/25
50/50 [==============================] - 0s 2ms/step - loss: 0.9398 - accuracy: 0.6600
Epoch 10/25
50/50 [==============================] - 0s 2ms/step - loss: 0.8589 - accuracy: 0.7106
Epoch 11/25
50/50 [

In [20]:
model.evaluate(X_testing, Y_testing)[1]

7/7 [==============================] - 0s 5ms/step - loss: 0.3154 - accuracy: 0.9400


0.9399999976158142

In [22]:
# creating an array of predictions from a matrix of percentages of classifications
def predictionrelease(predict):
    arr=[]
    for i in range(0,len(predict)):
        ans=np.argmax(predict[i])
        arr.append(ans)
    len(arr)
    return arr

In [23]:
#testing the cross value sets
predict_test = model.predict(X_testing)      
test_predict = predictionrelease(predict_test)

7/7 [==============================] - 0s 3ms/step


In [24]:
from sklearn.metrics import classification_report,confusion_matrix
#cross validation
print(classification_report(Y_testing,test_predict)) 

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        60
           1       0.93      0.95      0.94        41
           2       0.88      0.89      0.88        47
           3       0.94      0.92      0.93        52

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200

